[package]
name = "cli_tool"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["hackingpractise"]
description = "cli tools to create symbolic links from one directory to another"

[dependencies]
anyhow = "1.0.93"
clap = { version = "4.5.21", features = ["derive"] }
